package swingpractice;

import javax.swing.Action;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class FileMenu extends JMenu 
{
//	I don't know what this means but my IDE really wanted it to be here
	private static final long serialVersionUID = 1L;
	
	public void newGameMethod()
	{
		System.out.println("newgame");
	}
	
	public void undoMoveMethod()
	{
		System.out.println("undo undo undo");
	}
	
	public void init()
	{
		JMenuItem newGame = new JMenuItem("New Game");
		newGame.addActionListener(e -> newGameMethod());
		this.add(newGame);
		
		JMenuItem undoMove = new JMenuItem("Undo move");
		undoMove.addActionListener(e -> undoMoveMethod());
		this.add(undoMove);
		
	}


//this is the constructor I am planning on using
	public FileMenu() 
	{
		super("File");
		this.init();
	}


//These constructors were autogenerated
	public FileMenu(Action a) {
		super(a);
		// TODO Auto-generated constructor stub
	}



	public FileMenu(String s, boolean b) {
		super(s, b);
		// TODO Auto-generated constructor stub
	}



	public FileMenu(String s) {
		super(s);
		// TODO Auto-generated constructor stub
	}
	
//	FileMenu()
//	{
//		this.setName("al;ksdjf");
//		
//
//	}

}
